-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object exposing (..)


type Chapter
    = Chapter


type ChapterPreviousValues
    = ChapterPreviousValues


type ChapterSubscriptionPayload
    = ChapterSubscriptionPayload


type File
    = File


type FilePreviousValues
    = FilePreviousValues


type FileSubscriptionPayload
    = FileSubscriptionPayload


type QueryMeta_
    = QueryMeta_


type Section
    = Section


type SectionPreviousValues
    = SectionPreviousValues


type SectionSubscriptionPayload
    = SectionSubscriptionPayload


type SigninPayload
    = SigninPayload


type User
    = User


type UserPreviousValues
    = UserPreviousValues


type UserSubscriptionPayload
    = UserSubscriptionPayload
