-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object.FileSubscriptionPayload exposing (..)

import API.Enum.ModelMutationType_
import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) API.Object.FileSubscriptionPayload
selection constructor =
    Object.selection constructor


mutation : Field API.Enum.ModelMutationType_.ModelMutationType_ API.Object.FileSubscriptionPayload
mutation =
    Object.fieldDecoder "mutation" [] API.Enum.ModelMutationType_.decoder


node : SelectionSet decodesTo API.Object.File -> Field (Maybe decodesTo) API.Object.FileSubscriptionPayload
node object =
    Object.selectionField "node" [] object (identity >> Decode.maybe)


updatedFields : Field (Maybe (List String)) API.Object.FileSubscriptionPayload
updatedFields =
    Object.fieldDecoder "updatedFields" [] (Decode.string |> Decode.list |> Decode.maybe)


previousValues : SelectionSet decodesTo API.Object.FilePreviousValues -> Field (Maybe decodesTo) API.Object.FileSubscriptionPayload
previousValues object =
    Object.selectionField "previousValues" [] object (identity >> Decode.maybe)
