-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object.FilePreviousValues exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) API.Object.FilePreviousValues
selection constructor =
    Object.selection constructor


contentType : Field String API.Object.FilePreviousValues
contentType =
    Object.fieldDecoder "contentType" [] Decode.string


createdAt : Field API.Scalar.DateTime API.Object.FilePreviousValues
createdAt =
    Object.fieldDecoder "createdAt" [] (Decode.string |> Decode.map API.Scalar.DateTime)


id : Field API.Scalar.Id API.Object.FilePreviousValues
id =
    Object.fieldDecoder "id" [] (Decode.string |> Decode.map API.Scalar.Id)


name : Field String API.Object.FilePreviousValues
name =
    Object.fieldDecoder "name" [] Decode.string


secret : Field String API.Object.FilePreviousValues
secret =
    Object.fieldDecoder "secret" [] Decode.string


size : Field Int API.Object.FilePreviousValues
size =
    Object.fieldDecoder "size" [] Decode.int


updatedAt : Field API.Scalar.DateTime API.Object.FilePreviousValues
updatedAt =
    Object.fieldDecoder "updatedAt" [] (Decode.string |> Decode.map API.Scalar.DateTime)


url : Field String API.Object.FilePreviousValues
url =
    Object.fieldDecoder "url" [] Decode.string
