-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object.File exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) API.Object.File
selection constructor =
    Object.selection constructor


contentType : Field String API.Object.File
contentType =
    Object.fieldDecoder "contentType" [] Decode.string


createdAt : Field API.Scalar.DateTime API.Object.File
createdAt =
    Object.fieldDecoder "createdAt" [] (Decode.string |> Decode.map API.Scalar.DateTime)


id : Field API.Scalar.Id API.Object.File
id =
    Object.fieldDecoder "id" [] (Decode.string |> Decode.map API.Scalar.Id)


name : Field String API.Object.File
name =
    Object.fieldDecoder "name" [] Decode.string


secret : Field String API.Object.File
secret =
    Object.fieldDecoder "secret" [] Decode.string


size : Field Int API.Object.File
size =
    Object.fieldDecoder "size" [] Decode.int


updatedAt : Field API.Scalar.DateTime API.Object.File
updatedAt =
    Object.fieldDecoder "updatedAt" [] (Decode.string |> Decode.map API.Scalar.DateTime)


url : Field String API.Object.File
url =
    Object.fieldDecoder "url" [] Decode.string
