-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object.UserPreviousValues exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) API.Object.UserPreviousValues
selection constructor =
    Object.selection constructor


auth0UserId : Field (Maybe String) API.Object.UserPreviousValues
auth0UserId =
    Object.fieldDecoder "auth0UserId" [] (Decode.string |> Decode.maybe)


createdAt : Field API.Scalar.DateTime API.Object.UserPreviousValues
createdAt =
    Object.fieldDecoder "createdAt" [] (Decode.string |> Decode.map API.Scalar.DateTime)


id : Field API.Scalar.Id API.Object.UserPreviousValues
id =
    Object.fieldDecoder "id" [] (Decode.string |> Decode.map API.Scalar.Id)


updatedAt : Field API.Scalar.DateTime API.Object.UserPreviousValues
updatedAt =
    Object.fieldDecoder "updatedAt" [] (Decode.string |> Decode.map API.Scalar.DateTime)
