-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object.UserSubscriptionPayload exposing (..)

import API.Enum.ModelMutationType_
import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) API.Object.UserSubscriptionPayload
selection constructor =
    Object.selection constructor


mutation : Field API.Enum.ModelMutationType_.ModelMutationType_ API.Object.UserSubscriptionPayload
mutation =
    Object.fieldDecoder "mutation" [] API.Enum.ModelMutationType_.decoder


node : SelectionSet decodesTo API.Object.User -> Field (Maybe decodesTo) API.Object.UserSubscriptionPayload
node object =
    Object.selectionField "node" [] object (identity >> Decode.maybe)


updatedFields : Field (Maybe (List String)) API.Object.UserSubscriptionPayload
updatedFields =
    Object.fieldDecoder "updatedFields" [] (Decode.string |> Decode.list |> Decode.maybe)


previousValues : SelectionSet decodesTo API.Object.UserPreviousValues -> Field (Maybe decodesTo) API.Object.UserSubscriptionPayload
previousValues object =
    Object.selectionField "previousValues" [] object (identity >> Decode.maybe)
