-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Enum.ChapterOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ChapterOrderBy
    = CreatedAt_ASC
    | CreatedAt_DESC
    | Id_ASC
    | Id_DESC
    | Number_ASC
    | Number_DESC
    | Part_ASC
    | Part_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


decoder : Decoder ChapterOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "number_ASC" ->
                        Decode.succeed Number_ASC

                    "number_DESC" ->
                        Decode.succeed Number_DESC

                    "part_ASC" ->
                        Decode.succeed Part_ASC

                    "part_DESC" ->
                        Decode.succeed Part_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid ChapterOrderBy type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ChapterOrderBy -> String
toString enum =
    case enum of
        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Number_ASC ->
            "number_ASC"

        Number_DESC ->
            "number_DESC"

        Part_ASC ->
            "part_ASC"

        Part_DESC ->
            "part_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"
