-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Enum.FileOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type FileOrderBy
    = ContentType_ASC
    | ContentType_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | Id_ASC
    | Id_DESC
    | Name_ASC
    | Name_DESC
    | Secret_ASC
    | Secret_DESC
    | Size_ASC
    | Size_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC
    | Url_ASC
    | Url_DESC


decoder : Decoder FileOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "contentType_ASC" ->
                        Decode.succeed ContentType_ASC

                    "contentType_DESC" ->
                        Decode.succeed ContentType_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "name_ASC" ->
                        Decode.succeed Name_ASC

                    "name_DESC" ->
                        Decode.succeed Name_DESC

                    "secret_ASC" ->
                        Decode.succeed Secret_ASC

                    "secret_DESC" ->
                        Decode.succeed Secret_DESC

                    "size_ASC" ->
                        Decode.succeed Size_ASC

                    "size_DESC" ->
                        Decode.succeed Size_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    "url_ASC" ->
                        Decode.succeed Url_ASC

                    "url_DESC" ->
                        Decode.succeed Url_DESC

                    _ ->
                        Decode.fail ("Invalid FileOrderBy type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : FileOrderBy -> String
toString enum =
    case enum of
        ContentType_ASC ->
            "contentType_ASC"

        ContentType_DESC ->
            "contentType_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Name_ASC ->
            "name_ASC"

        Name_DESC ->
            "name_DESC"

        Secret_ASC ->
            "secret_ASC"

        Secret_DESC ->
            "secret_DESC"

        Size_ASC ->
            "size_ASC"

        Size_DESC ->
            "size_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"

        Url_ASC ->
            "url_ASC"

        Url_DESC ->
            "url_DESC"
