-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Enum.ModelMutationType_ exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ModelMutationType_
    = Created
    | Updated
    | Deleted


decoder : Decoder ModelMutationType_
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CREATED" ->
                        Decode.succeed Created

                    "UPDATED" ->
                        Decode.succeed Updated

                    "DELETED" ->
                        Decode.succeed Deleted

                    _ ->
                        Decode.fail ("Invalid ModelMutationType_ type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ModelMutationType_ -> String
toString enum =
    case enum of
        Created ->
            "CREATED"

        Updated ->
            "UPDATED"

        Deleted ->
            "DELETED"
