-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Enum.SectionOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type SectionOrderBy
    = Id_ASC
    | Id_DESC
    | Title_ASC
    | Title_DESC


decoder : Decoder SectionOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "title_ASC" ->
                        Decode.succeed Title_ASC

                    "title_DESC" ->
                        Decode.succeed Title_DESC

                    _ ->
                        Decode.fail ("Invalid SectionOrderBy type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : SectionOrderBy -> String
toString enum =
    case enum of
        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Title_ASC ->
            "title_ASC"

        Title_DESC ->
            "title_DESC"
