-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Enum.UserOrderBy exposing (..)

import Json.Decode as Decode exposing (Decoder)


type UserOrderBy
    = Auth0UserId_ASC
    | Auth0UserId_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | Id_ASC
    | Id_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


decoder : Decoder UserOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "auth0UserId_ASC" ->
                        Decode.succeed Auth0UserId_ASC

                    "auth0UserId_DESC" ->
                        Decode.succeed Auth0UserId_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid UserOrderBy type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : UserOrderBy -> String
toString enum =
    case enum of
        Auth0UserId_ASC ->
            "auth0UserId_ASC"

        Auth0UserId_DESC ->
            "auth0UserId_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"
